# Generated by Django 5.0.3 on 2024-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=1000)),
                ('short_url', models.CharField(max_length=1000)),
                ('visits', models.IntegerField(default=0)),
                ('page_title', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
